version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: seu_banco_de_dados
      MYSQL_USER: seu_usuario
      MYSQL_PASSWORD: sua_senha
      MYSQL_ROOT_PASSWORD: sua_senha_root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/seu_banco_de_dados
      SPRING_DATASOURCE_USERNAME: seu_usuario
      SPRING_DATASOURCE_PASSWORD: sua_senha
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-data:
